# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cc5UMYPjUNlvx0py1tP3W8eU1eWf7icn
"""

def kasallik_tashxisi(belgi):
    if belgi == "isitma":
        return "Parasetamol iching"
    elif belgi == "tish og'rig'i":
        return "Qupen iching"
    elif belgi == "qorin og'rig'i":
        return "Levomitsin iching"
    elif belgi == "yo'tal":
        return "Mukaltin iching"
    elif belgi == "bosh og'rig'i":
        return "Analgin iching"
    elif belgi == "allergiya":
        return "Tavegil iching"
    elif belgi == "ich qotishi":
        return "Dufalak iching"
    elif belgi == "qonli yiring":
        return "Furacilin bilan yuvib ko'ring"
    elif belgi == "ko'z og'rig'i":
        return "Oftalmol iching"
    elif belgi == "mushak og'rig'i":
        return "Diklofenak surting"
    else:
        return "Shifokorga murojaat qiling"

belgi = input("Kasallik belgisini kiriting: ")
natija = kasallik_tashxisi(belgi)
print(natija)

def kitob_tavsifi(kitob):
    if kitob == "1984":
        return ("1984 - George Orwell tomonidan yozilgan distopik roman. Kitob erkinlikni va nazoratni tasvirlaydi.",
                "1984, totalitar jamiyatda yashayotgan bosh qahramon Winston Smithning hikoyasini aytib beradi.")
    elif kitob == "Uyg'onish":
        return ("Uyg'onish - Franz Kafka tomonidan yozilgan mashhur roman. Asar, insonning o'zligini topishga bo'lgan kurashini ko'rsatadi.",
                "Asarda bosh qahramon Gregor Samsaning notanish tarzda qo'ziqorin kabi aylanib qolganligi tasvirlanadi.")
    elif kitob == "Shaytanat":
        return ("Shaytanat - Fyodor Dostoevskiy tomonidan yozilgan roman. Asarda insonning ichki kurashlari va axloqiy savollar ko'tariladi.",
                "Roman bosh qahramoni, o'zining maqsadlariga erishish yo'lida axloqiy qiymatlarni unutgan kishining tasviridir.")
    elif kitob == "Gurur va Qayg'u":
        return ("Gurur va Qayg'u - Jane Austen tomonidan yozilgan klassik roman. Kitobda oilalar va jamiyatning o'zaro munosabatlari tasvirlanadi.",
                "Asarda Elizabeth Bennet va Mr. Darcy o'rtasidagi murakkab munosabatlar va o'zgarishlar ko'rsatilgan.")
    elif kitob == "Alkimyogar":
        return ("Alkimyogar - Paulo Coelho tomonidan yozilgan roman. Kitob, o'z orzulariga erishish yo'lidagi sayohat haqida.",
                "Asarda Santiago ismli yigitning o'zining hayotiy orzularini amalga oshirish uchun boshlagan sarguzashtlari tasvirlanadi.")
    elif kitob == "Kichik Prens":
        return ("Kichik Prens - Antoine de Saint-Exupéry tomonidan yozilgan boshqacha hikoya. Asarda bolalik, hayot va insoniy qadriyatlar tasvirlanadi.",
                "Kichik Prens o'z sayohatida hayotning haqiqiy qadriyatlarini o'rganadi, va bu har bir kishiga katta saboq beradi.")
    elif kitob == "Dorian Greyning Portreti":
        return ("Dorian Greyning Portreti - Oscar Wilde tomonidan yozilgan roman. Kitob go'zallik, yosh va axloqiy degeneratsiya haqida.",
                "Asarda Dorian Grey ismli yosh yigitning portreti uning yashash va axloqiy qarorlaridagi o'zgarishlarni aks ettiradi.")
    elif kitob == "O'lim va qiz":
        return ("O'lim va qiz - Elie Wiesel tomonidan yozilgan kitob, Shoah (Xolokost) haqida.",
                "Asar, Elie Wieselning o'zining va oilasining Xolokostda boshidan kechirganlarini tasvirlaydi.")
    elif kitob == "Muzlatilgan daryo":
        return ("Muzlatilgan daryo - Chingiz Aytmatov tomonidan yozilgan roman. Asar insoniyat va tabiatni o'zaro bog'laydi.",
                "Kitobda ajoyib tabiiy muhit va odamlar o'rtasidagi ulkan dramatik to'qnashuv tasvirlanadi.")
    elif kitob == "Harry Potter va Filosoflar toshi":
        return ("Harry Potter va Filosoflar toshi - J.K. Rowling tomonidan yozilgan fantastika romanining birinchi kitobi.",
                "Asar, sehr va jodugarlik dunyosiga kirgan Harry Potterning sarguzashtlarini tasvirlaydi.")
    else:
        return ("Bu kitob haqida ma'lumot topilmadi.", "")

# Foydalanuvchidan kitob nomini olish
kitob = input("Kitob nomini kiriting: ")

# Kitob tavsifi va qo'shimcha ma'lumotni olish
tavsif, qo'shimcha = kitob_tavsifi(kitob)

# Asosiy tavsifni chiqarish
print(f"{kitob}: {tavsif}")

# Qo'shimcha ma'lumot mavjud bo'lsa, uni chiqarish
if qo'shimcha:
    print(f"Qo'shimcha ma'lumot: {qo'shimcha}")